#!/usr/bin/env bash
# 刻晴 · 项目介绍 TTS 测试
# Requires the server to be running at 127.0.0.1:7860 and an existing
# output/ directory next to where this script is invoked from.
set -euo pipefail

curl -X POST http://127.0.0.1:7860/tts \
  -H "Content-Type: application/json" \
  -o output/intro_keqing.wav \
  --data-raw '{"text":"哼。居然要我亲自来做项目介绍……算了，既然接了任务，就好好完成。这里是 Bert-VITS2 C++ 运行时。定位很明确：一个语音合成引擎。把文字转成声音。没有花里胡哨的东西。专注。高效。下面说正事。第一，语言支持。中文。日文。英文。三种语言可以混在同一句话里。システムは自動的に言語を検出して、スクリプトブロックごとに適切なフロントエンドを割り当てます。中国語はピンインと声調システムを使います。日本語は形態素解析とアクセント処理を行います。英語は発音辞書を参照します。認識精度は高く、処理速度も問題ありません。では、ここから英語で説明してみよう。Now let me switch to English for a moment. This is a demonstration of the trilingual synthesis capability. The system can detect and process Chinese, Japanese, and English within a single request, all in real time. Each tongue gets its own dedicated BERT-based frontend for accurate pronunciation and natural prosody. The underlying model is a VITS generator exported from PyTorch to ONNX format, with multi-head attention flow layers and a HiFi-GAN decoder. It runs on Windows, Linux, and macOS, with native GPU acceleration on all three platforms via CUDA and Metal. The quality is quite good, and the inference speed is very acceptable even for long paragraphs. 好了，英语说得够多了，回到中文。第二，跨平台。三大桌面系统都能跑。macOSのApple Siliconでは、ネイティブのMetalアクセラレーションを利用して、ONNXランタイムの中間層をバイパスします。これにより、CPUモードと比べて大幅な速度向上を実現しています。十分な最適化が施されていると言えるでしょう。第三，网络服务。一行命令启动。内置了完整的接口。支持一次性合成，返回完整的音频文件。ストリーミング出力にも対応しています。長文は自動的に文単位で分割され、PCMオーディオチャンクが順次返されます。受け取ったそばから再生できるので、全文の合成が終わるまで待つ必要はありません。APIの設計はシンプルで、レスポンスも高速です。テスト済みです。第四，音色。現在、六名の話者が利用可能です。日本語話者は四名：ナヒーダ、イリヤ、ソラ、そして立華奏。中国語と英語は各一名、どちらも私、刻晴です。どの声を選んでも構いませんが、私の声を推奨します。最も効率的ですから。第五，使用方法。簡単すぎて説明することもないくらいです。ターミナルでコマンドを一行入力するだけ。テキストを指定し、言語を選び、話者を選択して、エンターを押す。それだけです。もしアプリケーションに組み込むなら、HTTPインターフェースを直接呼び出してください。一行のcurlコマンドで合成結果を取得できます。すでに繰り返し検証済みで、問題はありません。また、このプロジェクトは完全にオープンソースです。コードはすべて公開されています。自由に使って、自由に改変してください。何か足りない点があれば、自分で手を動かしなさい。口だけでは何も変わりません。もう少し補足します。このエンジンには様々な最適化が施されています。意味特徴の抽出は全自動で、三言語それぞれに専用の文脈理解モデルが事前学習されています。推論時にこの意味モジュールを無効化して、計算リソースを節約することも可能です。モデルのパラメータも細かく調整できます。話速。ノイズレベル。乱数の初期値。すべて制御可能です。長文は自動的にチャンク分割され、チャンク間には自動で無音区間が挿入されます。自動的な文分割を無効にすることもできます。結論。これは十分にテストされた、信頼性が高く効率的なツールです。必要なものはすべて揃っており、余計なものは一切ありません。文字を声に変える機能が必要なら、もう探す必要はありません。これを使ってください。効率第一。以上。","language":"MIX","speaker_name":"keqing_zh","length_scale":1.1}'